name: funnums
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: 6.1.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  path_provider: 2.1.1
  lottie: 2.6.0
  connectivity_plus: 5.0.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.0
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true  
  image_path: "assets/icons/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animated_emoji/
    - assets/icons/
